[project]
name = "flask-form-fillup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "faker>=33.1.0",
    "flask>=3.1.0",
    "sqlmodel>=0.0.22",
]
